#!/usr/bin/env python3
"""Build assets/logo.svg — the ThingsBoard wordmark, recoloured for the prototype.

TWO symbols come out of the one brand file, because the file is two things:

  tb-logo      the lockup exactly as supplied — mark, "ThingsBoard", and the small
               "License Portal" caption beneath it.
  tb-wordmark  the same lockup with that caption dropped, for the places that set
               "License Portal" as real text beside the mark instead of baking it
               into a drawing (the header does, since 2026-09-29).

⚠️ THE SPLIT IS NOT A GUESS. The brand file keeps the caption as its own top-level
<g>, and labels it `aria-label="License Portal"` itself; this script asserts on that
label rather than counting paths or slicing by coordinate. If a future brand file
merges the two, the assert fails loudly instead of silently shipping half a logo.

The source is the brand file as supplied (`assets/logo_title_white_ls.svg`), which is
drawn in WHITE for a dark background. The prototype's ground is light, so every fill is
rewritten to `currentColor` and the placement rule colours it — black by default, and
whatever the surface needs anywhere else. Same mechanism as the icons: one <symbol>,
placed with <use>, coloured by CSS.

⚠️ THE MARK IS NOT AN ICON. It does not live in icons.svg and it is not from Tabler —
it is the product's own identity, the one drawing in the prototype that has to be itself.
It is kept in its own file so the icon rule ("nothing draws but icons.svg") can name
exactly one exception instead of leaving a loophole.

Usage:  python3 tools/build-logo.py [--check]
"""
import io, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'assets', 'logo_title_white_ls.svg')
OUT  = os.path.join(ROOT, 'assets', 'logo.svg')


# ⚠️ MEASURED, NOT DERIVED. The caption group is dropped from the markup, but the
# viewBox is a stated number and nothing in an SVG file recomputes it. getBBox() on the
# surviving group, read in the browser 2026-09-29 and rounded outward: 0 0 1450.98 300.87.
# ⚠️ The crop is SMALL, and that is not a mistake. The caption does not sit under the
# whole lockup — it sits under the word, to the RIGHT of the mark (x 952 -> 1453,
# y 258.6 -> 320), and the hexagon runs the full height on its own (y 0 -> 300.87). So
# dropping it buys 19px of height, not 80: the ratio goes 4.54:1 -> 4.82:1.
# Re-measure if the brand file is ever replaced.
WORDMARK_VB = '0 0 1451 301'


def split_top_level_groups(inner):
    """The source's top-level <g> elements, in order, as (start, end) slices."""
    out, depth, start = [], 0, None
    for m in re.finditer(r'<(/?)g\b[^>]*?(/?)>', inner):
        close, self_closing = m.group(1), m.group(2)
        if self_closing:
            continue
        if not close:
            if depth == 0:
                start = m.start()
            depth += 1
        else:
            depth -= 1
            if depth == 0:
                out.append((start, m.end()))
    return out


def build():
    s = io.open(SRC, encoding='utf-8').read()
    vb = re.search(r'viewBox="([^"]+)"', s).group(1)
    inner = s[s.index('>', s.index('<svg')) + 1:s.rindex('</svg>')]
    # every colour becomes the text colour; nothing may paint itself
    inner = re.sub(r'fill="(?!none\b)[^"]*"', 'fill="currentColor"', inner)
    inner = re.sub(r'stroke="(?!none\b)[^"]*"', 'stroke="currentColor"', inner)
    # ⚠️ Check PAINT, not every hex in the file. Inkscape leaves `text-decoration-color`
    # in a style soup on most paths; it colours nothing and rewriting it would be noise.
    # What must not survive is a fill or a stroke that paints itself.
    left = re.findall(r'(?:fill|stroke)="(#[0-9a-fA-F]{3,8}|rgb[^"]*)"', inner)
    left += re.findall(r'style="[^"]*?(?<!-)(?:fill|stroke):\s*(#[0-9a-fA-F]{3,8}|rgb[^;"]*)', inner)
    if left:
        raise SystemExit('colour survived the rewrite: %s' % left[:3])

    # the caption is a sibling group the brand file names itself — find it by that name
    groups = split_top_level_groups(inner)
    if len(groups) != 2:
        raise SystemExit('expected 2 top-level groups in the brand file, found %d' % len(groups))
    captions = [g for g in groups if 'aria-label="License Portal"' in inner[g[0]:g[1]]]
    if len(captions) != 1:
        raise SystemExit('could not identify the "License Portal" caption group')
    a, b = captions[0]
    wordmark = (inner[:a] + inner[b:]).strip()
    if 'aria-label="License Portal"' in wordmark:
        raise SystemExit('caption survived the split')

    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!-- GENERATED by tools/build-logo.py from assets/%s - do not edit by hand.\n'
            '     Every fill is currentColor, so CSS decides the colour. -->\n'
            '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n'
            '  <symbol id="tb-logo" viewBox="%s" fill="currentColor">%s</symbol>\n'
            '  <!-- the same lockup without the baked-in "License Portal" caption -->\n'
            '  <symbol id="tb-wordmark" viewBox="%s" fill="currentColor">%s</symbol>\n'
            '</svg>\n') % (os.path.basename(SRC), vb, inner, WORDMARK_VB, wordmark)


if __name__ == '__main__':
    out = build()
    if '--check' in sys.argv:
        cur = io.open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        raise SystemExit(0 if cur == out else 'assets/logo.svg is stale - re-run tools/build-logo.py')
    tmp = OUT + '.tmp'
    io.open(tmp, 'w', encoding='utf-8').write(out)
    os.replace(tmp, OUT)
    print('wrote %s' % OUT)
