#!/usr/bin/env python3
"""Build assets/logo.svg — the ThingsBoard wordmark, recoloured for the prototype.

The source is the brand file as supplied (`assets/logo_title_white_ls.svg`), which is
drawn in WHITE for a dark background. The prototype's ground is light, so every fill is
rewritten to `currentColor` and the placement rule colours it — black by default, and
whatever the surface needs anywhere else. Same mechanism as the icons: one <symbol>,
placed with <use>, coloured by CSS.

⚠️ THE MARK IS NOT AN ICON. It does not live in icons.svg and it is not from Tabler —
it is the product's own identity, the one drawing in the prototype that has to be itself.
It is kept in its own file so the icon rule ("nothing draws but icons.svg") can name
exactly one exception instead of leaving a loophole.

Usage:  python3 tools/build-logo.py [--check]
"""
import io, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'assets', 'logo_title_white_ls.svg')
OUT  = os.path.join(ROOT, 'assets', 'logo.svg')


def build():
    s = io.open(SRC, encoding='utf-8').read()
    vb = re.search(r'viewBox="([^"]+)"', s).group(1)
    inner = s[s.index('>', s.index('<svg')) + 1:s.rindex('</svg>')]
    # every colour becomes the text colour; nothing may paint itself
    inner = re.sub(r'fill="(?!none\b)[^"]*"', 'fill="currentColor"', inner)
    inner = re.sub(r'stroke="(?!none\b)[^"]*"', 'stroke="currentColor"', inner)
    # ⚠️ Check PAINT, not every hex in the file. Inkscape leaves `text-decoration-color`
    # in a style soup on most paths; it colours nothing and rewriting it would be noise.
    # What must not survive is a fill or a stroke that paints itself.
    left = re.findall(r'(?:fill|stroke)="(#[0-9a-fA-F]{3,8}|rgb[^"]*)"', inner)
    left += re.findall(r'style="[^"]*?(?<!-)(?:fill|stroke):\s*(#[0-9a-fA-F]{3,8}|rgb[^;"]*)', inner)
    if left:
        raise SystemExit('colour survived the rewrite: %s' % left[:3])
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!-- GENERATED by tools/build-logo.py from assets/%s - do not edit by hand.\n'
            '     Every fill is currentColor, so CSS decides the colour. -->\n'
            '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n'
            '  <symbol id="tb-logo" viewBox="%s" fill="currentColor">%s</symbol>\n'
            '</svg>\n') % (os.path.basename(SRC), vb, inner)


if __name__ == '__main__':
    out = build()
    if '--check' in sys.argv:
        cur = io.open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        raise SystemExit(0 if cur == out else 'assets/logo.svg is stale - re-run tools/build-logo.py')
    tmp = OUT + '.tmp'
    io.open(tmp, 'w', encoding='utf-8').write(out)
    os.replace(tmp, OUT)
    print('wrote %s' % OUT)
